### ISSUE TITLE
Not an issue :)

### ISSUE THREAD

**Issue by alexisju** [aquaris-dev/DEPRECATED_android_device_bq_gohan#1]
Just a message to let you know that it is nice to see your CM port for to the X5 Plus progressing.

Do you have some information to share? (About roadmap, difficulties, progress, etc?)

Do you plan to make this devices officially supported by CM community ?

There is also [another port in progress](https://github.com/x5plus-dev/android_device_bq_gohan) for this device, maybe you could join your forces? (It is more a question than a suggestion. I guess they are good reasons).

**Comment by Kra1o5** [comment]
Hi @alexisju ,

We are working on it, some issues left but not ETAs.

Already we are a good team.

Greetings
